import os
import json
from .feature2data import *
from predict_model.utils.dataset import *
from predict_model.test import apk_predict
from predict_model.train import *


class RES_Analyze:
    def __init__(self):
        # self.apk_name = apk_name
        # self.apk_path = os.path.join("apks_json",apk_name)
        pass
    
    def permisson_des(self,input_str):
        info_array = [
            {"keyword": "READ_CONTACTS", "info": ["危险","1","允许应用读取用户联系人数据。"]},
            {"keyword": "WRITE_CONTACT", "info": ["危险","1","允许应用写入用户联系人数据。"]},
            {"keyword": "GET_ACCOUNTS", "info": ["危险","1","允许访问账户服务中的账户列表。"]},
            {"keyword": "READ_CALENDAR", "info": ["危险","1","允许应用读取用户日历数据。"]},        
            {"keyword": "WRITE_CALENDAR", "info": ["危险","1","允许应用写入用户日历数据。"]},
            {"keyword": "SEND_SMS", "info": ["危险","1","允许应用发送短信。"]},
            {"keyword": "RECEIVE_SMS", "info": ["危险","1","允许应用接收短信。"]},        
            {"keyword": "READ_SMS", "info": ["危险","1","允许应用访问SMS信息。"]},
            {"keyword": "RECEIVE_WAP_PUSH", "info": ["危险","1","允许应用接收WAP推送信息。"]},
            {"keyword": "RECEIVE_MMS", "info": ["危险","1","允许应用监视传入的彩信。"]},        
            {"keyword": "READ_CELL_BROADCASTS", "info": ["危险","-","允许应用读取小区广播消息。"]},
            {"keyword": "READ_EXTERNAL_STORAGE", "info": ["危险","16","允许应用读取扩展存储。API级别Q以后不再建议使用。"]},
            {"keyword": "WRITE_EXTERNAL_STORAGE", "info": ["危险", "4", "允许应用写入扩展存储。API级别Q以后不再建议使用。"]},
            {"keyword": "ACCESS_FINE_LOCATION", "info": ["危险", "1", "允许应用访问精确的位置。"]},
            {"keyword": "ACCESS_COARSE_LOCATION", "info": ["危险", "1", "允许应用访问大概的位置。"]},
            {"keyword": "PROCESS_OUTGOING_CALLS", "info": ["危险", "1", "允许应用查看拨出呼叫期间拨出的号码。"]},
            {"keyword": "READ_CALL_LOG", "info": ["危险", "16", "允许应用读取用户通话日志。"]},
            {"keyword": "WRITE_CALL_LOG", "info": ["危险", "16", "允许应用写入用户通话日志。"]},
            {"keyword": "CALL_PHONE", "info": ["危险", "1", "允许应用在不经过拨号界面的情况下启动电话呼叫，以便用户确认呼叫。"]},
            {"keyword": "READ_PHONE_STATE", "info": ["危险", "1", "允许应用访问电话状态。"]},
            {"keyword": "USE_SIP", "info": ["危险", "9", "允许应用使用SIP服务。"]},
            {"keyword": "ADD_VOICEMAIL", "info": ["危险", "14", "允许应用向系统中添加语音邮件。"]},
            {"keyword": "ANSWER_PHONE_CALLS", "info": ["危险", "26", "允许应用接听来电。"]},
            {"keyword": "MANAGE_OWN_CALLS", "info": ["正常", "26", "允许调用应用通过自我管理的ConnectionService API管理自己的调用。"]},
            {"keyword": "READ_PHONE_NUMBERS", "info": ["危险", "26", "允许应用读取设备的电话号码。"]},
            {"keyword": "ACCEPT_HANDOVER", "info": ["危险", "28", "允许呼叫应用继续在其他应用中启动的呼叫。例如，视频通话应用希望在用户的移动网络上继续语音通话。"]},
            {"keyword": "ACCESS_UCE_PRESENCE_SERVICE", "info": ["签名|专用", "-", "允许应用访问UCE-Presence。"]},
            {"keyword": "ACCESS_UCE_OPTIONS_SERVICE", "info": ["签名|专用", "-", "允许应用访问UCE-OPTIONS。"]},
            {"keyword": "RECORD_AUDIO", "info": ["危险", "1", "允许应用录音。"]},
            {"keyword": "CAMERA", "info": ["危险|立即", "1", "允许访问摄像头。"]},
            {"keyword": "BODY_SENSORS", "info": ["危险", "20", "允许应用访问身体传感器的数据。"]},

            {"keyword": "ACCESS_LOCATION_EXTRA_COMMANDS", "info": ["正常","1","	允许程序获取额外的位置信息提供程序命令。"]},        
            {"keyword": "ACCESS_NETWORK_STATE", "info": ["正常|立即", "1", "允许应用获取网络信息状态。"]},
            {"keyword": "ACCESS_WIFI_STATE", "info": ["正常", "1", "允许应用获取当前WiFi接入的状态以及WLAN热点的信息。"]},
            {"keyword": "BLUETOOTH", "info": ["正常", "1", "允许程序连接配对过的蓝牙设备。"]},
            {"keyword": "BLUETOOTH_ADMIN", "info": ["正常", "1", "允许程序发现和配对新的蓝牙设备。"]},
            {"keyword": "BROADCAST_STICKY", "info": ["正常", "1", "允许应用发送持久广播。"]},
            {"keyword": "CHANGE_NETWORK_STATE", "info": ["正常", "1", "允许应用更改网络连接状态。"]},
            {"keyword": "CHANGE_WIFI_STATE", "info": ["正常", "1", "允许应用更改Wi-Fi连接状态。"]},
            {"keyword": "DELETE_PACKAGES", "info": ["正常", "1", "允许程序删除应用。对第三方应用不可用。"]},
            {"keyword": "DISABLE_KEYGUARD", "info": ["正常", "1", "允许应用停用键锁以及任何关联的密码安全措施。"]},
            {"keyword": "EXPAND_STATUS_BAR", "info": ["正常", "1", "允许程序展开/收拢状态栏。"]},
            {"keyword": "GET_PACKAGE_SIZE", "info": ["正常", "1", "允许应用计算应用存储空间。"]},
            {"keyword": "GET_TASKS", "info": ["正常", "1", "允许程序获取当前或最近运行的应用。API级别21以后不再建议使用。"]},
            {"keyword": "INTERNET", "info": ["正常|立即", "1", "允许应用访问网络连接。"]},
            {"keyword": "MODIFY_AUDIO_SETTINGS", "info": ["正常", "1", "允许应用修改全局声音设置。"]},
            {"keyword": "PERSISTENT_ACTIVITY", "info": ["正常", "1", "让应用始终运行。API级别15以后不再建议使用。"]},
            {"keyword": "READ_SYNC_SETTINGS", "info": ["正常", "1", "允许应用读取同步设置。"]},
            {"keyword": "READ_SYNC_STATS", "info": ["正常", "1", "允许应用读取同步状态。"]},
            {"keyword": "RECEIVE_BOOT_COMPLETED", "info": ["正常", "1", "允许应用开机启动。"]},
            {"keyword": "REORDER_TASKS", "info": ["正常", "1", "允许应用对正在运行的应用重新排序。"]},
            {"keyword": "RESTART_PACKAGES", "info": ["正常", "1", "允许应用关闭其他应用。API级别15以后不再建议使用。"]},
            {"keyword": "SET_WALLPAPER", "info": ["正常", "1", "允许应用设置壁纸。"]},
            {"keyword": "SET_WALLPAPER_HINTS", "info": ["正常", "1", "允许应用设置壁纸提示。"]},
            {"keyword": "VIBRATE", "info": ["正常|立即", "1", "允许应用使用震动。"]},
            {"keyword": "WAKE_LOCK", "info": ["正常", "1", "允许应用防止手机休眠。"]},
            {"keyword": "CHANGE_WIFI_MULTICAST_STATE", "info": ["正常", "4", "允许应用进入Wi-Fi多播模式。"]},
            {"keyword": "KILL_BACKGROUND_PROCESSES", "info": ["正常", "8", "允许应用关闭其他应用。"]},
            {"keyword": "NFC", "info": ["正常", "9", "允许应用通过NFC执行I/O操作。"]},
            {"keyword": "WRITE_SYNC_SETTINGS", "info": ["正常", "1", "允许应用写入同步设置。"]},
            {"keyword": "SET_ALARM", "info": ["正常", "9", "允许应用使用Intent通过广播设置闹钟。"]},
            {"keyword": "INSTALL_SHORTCUT", "info": ["正常", "19", "允许应用安装快捷方式。API级别26以后通过ShortcutManager.requestPinShortcut()实现。"]},
            {"keyword": "TRANSMIT_IR", "info": ["正常", "19", "允许应用使用设备的红外发射器。"]},
            {"keyword": "UNINSTALL_SHORTCUT", "info": ["正常", "19", "允许应用卸载快捷方式。"]},
            {"keyword": "ACCESS_NOTIFICATION_POLICY", "info": ["正常", "23", "允许应用读取和写入“勿扰”模式配置。"]},
            {"keyword": "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "info": ["正常", "23", "允许应用请求忽略电池优化。"]},
            {"keyword": "REQUEST_COMPANION_RUN_IN_BACKGROUND", "info": ["正常", "26", "允许应用在后台运行。"]},
            {"keyword": "REQUEST_COMPANION_USE_DATA_IN_BACKGROUND", "info": ["正常", "26", "允许应用在后台使用数据。"]},
            {"keyword": "REQUEST_DELETE_PACKAGES", "info": ["正常", "26", "允许应用程序请求删除软件包。"]},
            {"keyword": "FOREGROUND_SERVICE", "info": ["正常", "28", "允许应用使用前台服务。"]},
            {"keyword": "NFC_TRANSACTION_EVENT", "info": ["正常", "28", "允许应用接收NFC事务事件。"]},
            {"keyword": "CALL_COMPANION_APP", "info": ["正常", "Q", "允许实现InCallService API的应用有资格作为调用伴随应用启用。"]},
            {"keyword": "ACCESS_BACKGROUND_LOCATION", "info": ["危险", "Q", "允许应用在后台访问位置。如果请求这个权限，您还应该请求ACCESS_FINE_LOCATION。"]},
            {"keyword": "ACCESS_MEDIA_LOCATION", "info": ["-", "Q", "允许应用访问用户共享集合中保留的任何地理位置。"]},
            {"keyword": "ACTIVITY_RECOGNITION", "info": ["危险", "Q", "允许应用识别当前用户的物理活动。比如：行走，驾驶或者静止站立。"]},
            {"keyword": "BIND_SMS_APP_SERVICE", "info": ["-", "Q", "SmsAppService的子类必要。"]},
            {"keyword": "GET_AND_REQUEST_SCREEN_LOCK_COMPLEXITY", "info": ["正常", "Q", "允许应用获得屏幕锁定复杂度并提示用户，将屏幕锁定更新到特定的复杂性级别。"]},
            {"keyword": "READ_MEDIA_AUDIO", "info": ["-", "Q", "允许应用读取用户共享音频集合。"]},
            {"keyword": "READ_MEDIA_IMAGES", "info": ["-", "Q", "允许应用读取用户共享图像集合。"]},
            {"keyword": "READ_MEDIA_VIDEO", "info": ["-", "Q", "允许应用读取用户共享视频集合。"]},
            {"keyword": "SMS_FINANCIAL_TRANSACTIONS", "info": ["-", "Q", "允许财务应用读取过滤信息。"]},
            {"keyword": "USE_FULL_SCREEN_INTENT", "info": ["-", "Q", "对于命中Build.VERSION_CODES.Q的想要使用通知全屏Intents的应用是必需的。"]},

            {"keyword": "ACCESS_CHECKIN_PROPERTIES", "info": ["签名|专用","	1","允许应用读取/写入登记check-in数据库属性表。对第三方应用不可用。"]},
            {"keyword": "ACCOUNT_MANAGER", "info": ["签名", "5", "允许应用获取账户验证信息。对第三方应用不可用。"]},
            {"keyword": "BATTERY_STATS", "info": ["签名|专用|开发", "1", "允许应用收集电池统计信息。"]},
            {"keyword": "BIND_ACCESSIBILITY_SERVICE", "info": ["签名", "16", "AccessibilityService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_APPWIDGET", "info": ["签名|专用", "3", "允许应用告诉AppWidget服务哪个应用可以访问AppWidget的数据。对第三方应用不可用。"]},
            {"keyword": "BIND_AUTOFILL_SERVICE", "info": ["签名", "26", "AutofillService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_CALL_REDIRECTION_SERVICE", "info": ["签名|专用", "Q", "CallRedirectionService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_CARRIER_MESSAGING_SERVICE", "info": ["签名|专用", "22", "API级别23以后不再建议使用，使用BIND_CARRIER_SERVICES"]},
            {"keyword": "BIND_CARRIER_SERVICES", "info": ["签名|专用", "23", "允许应用绑定到运营商服务。"]},
            {"keyword": "BIND_CHOOSER_TARGET_SERVICE", "info": ["签名", "23", "ChooserTargetService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_CONDITION_PROVIDER_SERVICE", "info": ["签名", "24", "ConditionProviderService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_DEVICE_ADMIN", "info": ["签名", "8", "系统管理员接收者必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_DREAM_SERVICE", "info": ["签名", "21", "DreamService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_INCALL_SERVICE", "info": ["签名|专用", "23", "InCallService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_INPUT_METHOD", "info": ["签名", "3", "InputMethodService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_MIDI_DEVICE_SERVICE", "info": ["签名", "23", "MidiDeviceService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_NFC_SERVICE", "info": ["签名", "19", "HostApduService或OffHostApduService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_NOTIFICATION_LISTENER_SERVICE", "info": ["签名", "18", "NotificationListenerService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_PRINT_SERVICE", "info": ["签名", "19", "PrintService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_QUICK_SETTINGS_TILE", "info": ["签名", "24", "允许应用绑定到第3方快速设置。TileService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_REMOTEVIEWS", "info": ["签名|专用", "11", "RemoteViewsService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_SCREENING_SERVICE", "info": ["签名|专用", "24", "CallScreeningService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_TELECOM_CONNECTION_SERVICE", "info": ["签名|专用", "23", "ConnectionService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_TEXT_SERVICE", "info": ["签名", "14", "TextService（比如SpellCheckerService）必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_TV_INPUT", "info": ["签名|专用", "21", "TvInputService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_VISUAL_VOICEMAIL_SERVICE", "info": ["签名|专用", "26", "链接VisualVoicemailService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_VOICE_INTERACTION", "info": ["签名", "21", "VoiceInteractionService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_VPN_SERVICE", "info": ["签名", "14", "VpnService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_VR_LISTENER_SERVICE", "info": ["签名", "24", "VrListenerService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_WALLPAPER", "info": ["签名|专用", "8", "WallpaperService必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BLUETOOTH_PRIVILEGED", "info": ["签名|专用", "19", "允许应用配对蓝牙设备而无需用户交互，并允许或禁止电话簿访问或消息访问。对第三方应用不可用。"]},
            {"keyword": "BROADCAST_PACKAGE_REMOVED", "info": ["签名", "1", "允许应用广播已删除应用包的通知。对第三方应用不可用。"]},
            {"keyword": "BROADCAST_SMS", "info": ["签名", "2", "允许应用广播短信息接收通知。对第三方应用不可用。"]},
            {"keyword": "BROADCAST_WAP_PUSH", "info": ["签名", "2", "允许应用广播WAP推送回执通知。对第三方应用不可用。"]},
            {"keyword": "CALL_PRIVILEGED", "info": ["签名|专用", "1", "允许应用调用任何电话号码，包括紧急号码，而无需通过拨号界面让用户确认正在呼叫。对第三方应用不可用。"]},
            {"keyword": "CAPTURE_AUDIO_OUTPUT", "info": ["签名|专用", "19", "允许应用捕获音频输出。对第三方应用不可用。"]},
            {"keyword": "CHANGE_COMPONENT_ENABLED_STATE", "info": ["签名|专用", "1", "允许应用改变组件启用状态（而不是其自己的组件）。对第三方应用不可用。"]},
            {"keyword": "CHANGE_CONFIGURATION", "info": ["签名|专用|开发", "1", "允许应用修改当前配置，如区域设置。"]},
            {"keyword": "CLEAR_APP_CACHE", "info": ["签名|专用", "1", "允许应用清除设备上所有已安装应用的缓存。"]},
            {"keyword": "CONTROL_LOCATION_UPDATES", "info": ["签名|专用", "1", "允许启用/禁止无线模块位置更新提示。对第三方应用不可用。"]},
            {"keyword": "DELETE_CACHE_FILES", "info": ["签名|专用", "1", "允许应用删除缓存文件。"]},
            {"keyword": "DIAGNOSTIC", "info": ["签名", "1", "允许应用将RW转换为诊断资源。对第三方应用不可用。"]},
            {"keyword": "DUMP", "info": ["签名|专用|开发", "1", "允许程序从系统服务获取系统dump信息。对第三方应用不可用。"]},
            {"keyword": "FACTORY_TEST", "info": ["签名", "1", "允许程序运行工厂测试模式。对第三方应用不可用。"]},
            {"keyword": "GLOBAL_SEARCH", "info": ["签名|专用", "4", "此权限用于内容提供程序，以允许全局搜索系统访问其数据。"]},
            {"keyword": "INSTALL_LOCATION_PROVIDER", "info": ["签名|专用", "4", "允许应用将位置提供程序安装到位置管理器中。对第三方应用不可用。"]},
            {"keyword": "INSTALL_PACKAGES", "info": ["签名|专用", "1", "允许应用安装APK。对第三方应用不可用。"]},
            {"keyword": "MANAGE_DOCUMENTS", "info": ["签名", "19", "允许应用管理访问文档，通常作为文档选取器的一部分。对第三方应用不可用。"]},
            {"keyword": "MASTER_CLEAR", "info": ["签名|专用", "1", "允许应用执行软格式化。对第三方应用不可用。"]},
            {"keyword": "MEDIA_CONTENT_CONTROL", "info": ["签名|专用", "19", "允许应用知道正在播放的内容并控制其播放。对第三方应用不可用。"]},
            {"keyword": "MODIFY_PHONE_STATE", "info": ["签名|专用", "1", "允许修改手机状态。对第三方应用不可用。"]},
            {"keyword": "MOUNT_FORMAT_FILESYSTEMS", "info": ["签名|专用", "3", "允许格式可移动存储。对第三方应用不可用。"]},
            {"keyword": "MOUNT_UNMOUNT_FILESYSTEMS", "info": ["签名|专用", "1", "允许挂载/卸载可移动存储。对第三方应用不可用。"]},
            {"keyword": "PACKAGE_USAGE_STATS", "info": ["签名|开发|立即|应用", "23", "允许应用收集组件使用统计信息。"]},
            {"keyword": "READ_FRAME_BUFFER", "info": ["签名|专用", "-", "允许应用读取帧缓存用于屏幕截图。对第三方应用不可用。"]},
            {"keyword": "READ_INPUT_STATE", "info": ["签名", "1", "允许应用检索按键和开关的当前状态。API级别16以后不再建议使用。对第三方应用不可用。"]},
            {"keyword": "READ_LOGS", "info": ["签名|专用|开发", "1", "允许应用读取系统底层日志。对第三方应用不可用。"]},
            {"keyword": "READ_VOICEMAIL", "info": ["签名|专用", "21", "允许应用读取系统语音邮件。"]},
            {"keyword": "REBOOT", "info": ["签名|专用", "1", "允许应用重启设备。对第三方应用不可用。"]},
            {"keyword": "SEND_RESPOND_VIA_MESSAGE", "info": ["签名|专用", "18", "在通话期间，允许应用(电话)向其他应用发送请求，处理respond-via-message动作。对第三方应用不可用。"]},
            {"keyword": "SET_ALWAYS_FINISH", "info": ["签名|专用|开发", "1", "允许应用控制在后台运行时是否立即结束活动。对第三方应用不可用。"]},
            {"keyword": "SET_ANIMATION_SCALE", "info": ["签名|专用|开发", "1", "修改全局动画比例因子。对第三方应用不可用。"]},
            {"keyword": "SET_DEBUG_APP", "info": ["签名|专用|开发", "1", "设置为Debug应用。对第三方应用不可用。"]},
            {"keyword": "SET_PREFERRED_APPLICATIONS", "info": ["签名|验证", "1", "允许应用设置首选应用。API级别15以后不再建议使用。"]},
            {"keyword": "SET_PROCESS_LIMIT", "info": ["签名|专用|开发", "1", "允许应用设置可以运行的最大（不需要的）进程数。对第三方应用不可用。"]},
            {"keyword": "SET_TIME", "info": ["签名|专用", "8", "允许应用设置系统时间。对第三方应用不可用。"]},
            {"keyword": "SET_TIME_ZONE", "info": ["签名|专用", "1", "允许应用设置系统时区。对第三方应用不可用。"]},
            {"keyword": "SIGNAL_PERSISTENT_PROCESSES", "info": ["签名|专用|开发", "1", "允许应用请求向所有持久进程发送信号。对第三方应用不可用。"]},
            {"keyword": "STATUS_BAR", "info": ["签名|专用", "1", "允许应用打开、关闭、禁用状态栏和图标。对第三方应用不可用。"]},
            {"keyword": "SYSTEM_ALERT_WINDOW", "info": ["签名|应用|开发|预安装", "1", "允许应用显示在其他应用上方。API级别23后不再建议使用。"]},
            {"keyword": "UPDATE_DEVICE_STATS", "info": ["签名|专用", "3", "允许应用更新设备状态。"]},
            {"keyword": "WRITE_APN_SETTINGS", "info": ["签名|专用", "1", "允许应用写入APN设置并读取现有APN设置的敏感字段。对第三方应用不可用。"]},
            {"keyword": "WRITE_GSERVICES", "info": ["签名|专用", "1", "允许应用修改Google服务地图。对第三方应用不可用。"]},
            {"keyword": "WRITE_SECURE_SETTINGS", "info": ["签名|专用|开发", "3", "允许应用读写安全系统设置。对第三方应用不可用。"]},
            {"keyword": "WRITE_SETTINGS", "info": ["签名|预安装|应用", "1", "允许应用读写系统设置。API级别23后不再建议使用。"]},
            {"keyword": "WRITE_VOICEMAIL", "info": ["签名|专用", "21", "允许应用修改删除系统语音邮件。"]},

            {"keyword": "ACCESS_AMBIENT_LIGHT_STATS", "info": ["签名|专用|开发","-","允许应用收集环境光状态。对第三方应用不可用。"]},
            {"keyword": "ACCESS_BROADCAST_RADIO", "info": ["签名|专用", "-", "允许访问广播电台。对第三方应用不可用。"]},
            {"keyword": "ACCESS_CACHE_FILESYSTEM", "info": ["签名|专用", "-", "允许应用读写缓存分区。"]},
            {"keyword": "ACCESS_CONTENT_PROVIDERS_EXTERNALLY", "info": ["签名", "-", "允许通过ApplicationThread外部访问内容提供程序。"]},
            {"keyword": "ACCESS_DRM_CERTIFICATES", "info": ["签名|专用", "-", "允许应用提供和访问DRM凭证。对第三方应用不可用。"]},
            {"keyword": "ACCESS_FM_RADIO", "info": ["签名|专用", "-", "允许访问FM。对第三方应用不可用。"]},
            {"keyword": "ACCESS_IMS_CALL_SERVICE", "info": ["签名|专用", "-", "允许程序使用即时通讯通话服务。"]},
            {"keyword": "ACCESS_INPUT_FLINGER", "info": ["签名", "-", "允许应用访问InputFlinger。"]},
            {"keyword": "ACCESS_INSTANT_APPS", "info": ["签名|安装|验证", "-", "允许访问和管理即时应用。"]},
            {"keyword": "ACCESS_KEYGUARD_SECURE_STORAGE", "info": ["签名", "-", "允许应用访问键盘安全存储。"]},
            {"keyword": "ACCESS_LOWPAN_STATE", "info": ["签名|专用", "-", "允许应用访问LoWPAN。对第三方应用不可用。"]},
            {"keyword": "ACCESS_MOCK_LOCATION", "info": ["签名", "1", "允许应用获取模拟定位信息。"]},
            {"keyword": "ACCESS_MTP", "info": ["签名|专用", "-", "允许应用访问MTP-USB内核驱动程序。仅用于设备端MTP实现。"]},
            {"keyword": "ACCESS_NETWORK_CONDITIONS", "info": ["签名|专用", "-", "允许应用监听网络状态。对第三方应用不可用。"]},
            {"keyword": "ACCESS_NOTIFICATIONS", "info": ["签名|专用|应用", "-", "允许应用程序读取当前通知集。"]},
            {"keyword": "ACCESS_PDB_STATE", "info": ["签名", "-", "允许查询PersistentDataBlock的状态。对第三方应用不可用。"]},
            {"keyword": "ACCESS_SHORTCUTS", "info": ["签名|文本分类器", "-", "允许访问所有应用快捷方式。"]},
            {"keyword": "ACCESS_SURFACE_FLINGER", "info": ["签名", "1", "允许应用访问Android平台上底层的图形显示支持。对第三方应用不可用。"]},
            {"keyword": "ACCESS_VOICE_INTERACTION_SERVICE", "info": ["签名", "-", "允许应用与当前语音交互服务交互。"]},
            {"keyword": "ACCESS_VR_MANAGER", "info": ["签名", "-", "允许应用访问IVrManager。"]},
            {"keyword": "ACCESS_VR_STATE", "info": ["签名|预安装", "-", "需要通过访问VR-Mode状态和状态更改事件。"]},
            {"keyword": "ACCESS_WIMAX_STATE", "info": ["正常", "-", "允许应用建立或中断WiMAX网络连接。"]},
            {"keyword": "ACTIVITY_EMBEDDING", "info": ["签名|专用|开发", "-", "允许应用嵌入其他Activity。"]},
            {"keyword": "ALLOCATE_AGGRESSIVE", "info": ["签名|专用", "-", "允许应用分配磁盘空间。对第三方应用不可用。"]},
            {"keyword": "ALLOW_ANY_CODEC_FOR_PLAYBACK", "info": ["签名|专用", "-", "允许应用在解码播放时使用任何媒体解码器。"]},
            {"keyword": "ASEC_ACCESS", "info": ["签名", "-", "允许应用访问ASEC无损API。"]},
            {"keyword": "ASEC_CREATE", "info": ["签名", "-", "允许创建ASEC卷。"]},
            {"keyword": "ASEC_DESTROY", "info": ["签名", "-", "允许销毁ASEC卷。"]},
            {"keyword": "ASEC_MOUNT_UNMOUNT", "info": ["签名", "-", "允许装载/卸载ASEC卷。"]},
            {"keyword": "ASEC_RENAME", "info": ["签名", "-", "允许为ASEC卷改名。"]},
            {"keyword": "BACKUP", "info": ["签名|专用", "-", "允许应用控制备份和还原过程。对第三方应用不可用。"]},
            {"keyword": "BIND_AUTOFILL_FIELD_CLASSIFICATION_SERVICE", "info": ["签名", "-", "允许应用访问AutofillFieldClassificationService。确保只有系统可以绑定到它。对第三方应用不可用。"]},
            {"keyword": "BIND_CACHE_QUOTA_SERVICE", "info": ["签名", "-", "允许应用访问CacheQuotaService。对第三方应用不可用。"]},
            {"keyword": "BIND_COMPANION_DEVICE_MANAGER_SERVICE", "info": ["签名", "-", "允许应用访问CompanionDeviceManager。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_CONNECTION_SERVICE", "info": ["签名|专用", "-", "允许应用绑定ConnectionService。"]},
            {"keyword": "BIND_DIRECTORY_SEARCH", "info": ["签名|专用", "-", "允许应用搜索联系人目录。这只能由ContactsProvider使用。对第三方应用不可用。"]},
            {"keyword": "BIND_EUICC_SERVICE", "info": ["签名", "-", "允许应用调用EuiccService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_IMS_SERVICE", "info": ["签名|专用", "-", "允许应用调用ImsService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_INTENT_FILTER_VERIFIER", "info": ["签名", "-", "允许过滤接收器。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_JOB_SERVICE", "info": ["签名", "-", "允许应用绑定任务服务。"]},
            {"keyword": "BIND_KEYGUARD_APPWIDGET", "info": ["签名|专用", "-", "允许在键盘添加小部件。"]},
            {"keyword": "BIND_NETWORK_RECOMMENDATION_SERVICE", "info": ["签名", "-", "允许系统绑定到发现的网络推荐服务。"]},
            {"keyword": "BIND_NOTIFICATION_ASSISTANT_SERVICE", "info": ["签名", "-", "允许应用访问NotificationAssistantService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_PACKAGE_VERIFIER", "info": ["签名", "-", "包验证接收器必要。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_PRINT_RECOMMENDATION_SERVICE", "info": ["签名", "-", "允许应用访问RecommendationService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_PRINT_SPOOLER_SERVICE", "info": ["签名", "-", "允许应用访问PrintSpooler。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_REMOTE_DISPLAY", "info": ["签名", "-", "允许应用访问RemoteDisplayProvider。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_RESOLVER_RANKER_SERVICE", "info": ["签名", "-", "允许应用扩展ResolverRankerService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_ROUTE_PROVIDER", "info": ["签名", "-", "允许应用访问MediaRouteService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_RUNTIME_PERMISSION_PRESENTER_SERVICE", "info": ["签名", "-", "允许应用访问RuntimePermissionPresenterService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_SETTINGS_SUGGESTIONS_SERVICE", "info": ["签名", "-", "允许应用绑定到建议服务。"]},
            {"keyword": "BIND_SOUND_TRIGGER_DETECTION_SERVICE", "info": ["签名", "-", "允许服务检测声音。"]},
            {"keyword": "BIND_TELEPHONY_DATA_SERVICE", "info": ["签名", "-", "允许应用使用电话数据服务。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_TELEPHONY_NETWORK_SERVICE", "info": ["签名", "-", "允许应用调用NetworkService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_TEXTCLASSIFIER_SERVICE", "info": ["签名", "-", "允许应用访问TextClassifierService。确保只有系统可以绑定到它。对第三方应用不可用。"]},
            {"keyword": "BIND_TRUST_AGENT", "info": ["签名", "-", "允许应用访问TrustAgentService。确保只有系统可以绑定到它。"]},
            {"keyword": "BIND_TV_REMOTE_SERVICE", "info": ["签名|专用", "-", "允许应用访问TvRemoteProvider。确保只有系统可以绑定到它。对第三方应用不可用。"]},
            {"keyword": "BLUETOOTH_MAP", "info": ["签名", "-", "控制对仅用于蓝牙的电子邮件提供商的访问。"]},
            {"keyword": "BLUETOOTH_STACK", "info": ["签名", "-", "允许蓝牙堆栈访问文件。只能由蓝牙APK使用。"]},
            {"keyword": "BRICK", "info": ["签名", "-", "允许应用禁用手机。对第三方应用不可用。"]},
            {"keyword": "BRIGHTNESS_SLIDER_USAGE", "info": ["签名|专用|开发", "-", "允许应用收集亮度滑块更改信息。对第三方应用不可用。"]},
            {"keyword": "BROADCAST_NETWORK_专用", "info": ["签名|专用", "-", "允许应用广播专用网络请求。对第三方应用不可用。"]},
            {"keyword": "CACHE_CONTENT", "info": ["签名", "-", "允许应用缓存内容。对第三方应用不可用。"]},
            {"keyword": "CAMERA_DISABLE_TRANSMIT_LED", "info": ["签名|专用", "-", "允许禁用应用使用相机时正常打开的传输指示灯LED。"]},
            {"keyword": "CAMERA_SEND_SYSTEM_EVENTS", "info": ["签名|专用", "-", "允许发送有关系统范围内事件的照相机服务通知。"]},
            {"keyword": "CAPTURE_AUDIO_HOTWORD", "info": ["签名|专用", "-", "允许应用捕获音频进行Hotword检测。对第三方应用不可用。"]},
            {"keyword": "CAPTURE_SECURE_VIDEO_OUTPUT", "info": ["签名|专用", "-", "允许应用捕获安全视频输出。对第三方应用不可用。"]},
            {"keyword": "CAPTURE_TV_INPUT", "info": ["签名|专用", "-", "允许捕获一帧电视输入硬件。对第三方应用不可用。"]},
            {"keyword": "CAPTURE_VIDEO_OUTPUT", "info": ["签名|专用", "-", "允许应用捕获视频输出。对第三方应用不可用。"]},
            {"keyword": "CHANGE_ACCESSIBILITY_VOLUME", "info": ["签名", "-", "允许应用更改辅助功能卷。"]},
            {"keyword": "CHANGE_APP_IDLE_STATE", "info": ["签名|专用", "-", "允许应用更改空闲状态。对第三方应用不可用。"]},
            {"keyword": "CHANGE_BACKGROUND_DATA_SETTING", "info": ["签名", "-", "允许应用更改后台数据设置。对第三方应用不可用。"]},
            {"keyword": "CHANGE_DEVICE_IDLE_TEMP_WHITELIST", "info": ["签名|专用", "-", "允许应用访问网络和获取唤醒锁。对第三方应用不可用。"]},
            {"keyword": "CHANGE_HDMI_CEC_ACTIVE_SOURCE", "info": ["签名|专用", "-", "允许应用更改HDMI-CEC活动源。对第三方应用不可用。"]},
            {"keyword": "CHANGE_LOWPAN_STATE", "info": ["签名|专用", "-", "允许应用更改LoWPAN状态。对第三方应用不可用。"]},
            {"keyword": "CHANGE_OVERLAY_PACKAGES", "info": ["签名|专用", "-", "允许应用更改资源覆盖的优先级。"]},
            {"keyword": "CHANGE_WIMAX_STATE", "info": ["正常", "-", "允许应用更改WiMAX状态。"]},
            {"keyword": "CLEAR_APP_GRANTED_URI_PERMISSIONS", "info": ["签名", "-", "允许应用清除其他应用的URI权限。对第三方应用不可用。"]},
            {"keyword": "CLEAR_APP_USER_DATA", "info": ["签名|专用", "1", "允许应用清除设备上所有已安装应用的用户数据。"]},
            {"keyword": "CONFIGURE_DISPLAY_BRIGHTNESS", "info": ["签名|专用|开发", "-", "允许应用修改亮度。"]},
            {"keyword": "CONFIGURE_DISPLAY_COLOR_MODE", "info": ["签名", "-", "允许应用控制颜色模式。对第三方应用不可用。"]},
            {"keyword": "CONFIGURE_WIFI_DISPLAY", "info": ["签名", "-", "允许应用配置并连接到WiFi显示器。"]},
            {"keyword": "CONFIRM_FULL_BACKUP", "info": ["签名", "-", "允许包启动安全完整备份确认UI。确保只有系统可以绑定到它。"]},
            {"keyword": "CONNECTIVITY_INTERNAL", "info": ["签名|专用", "-", "允许应用使用ConnectivityManager专用API。"]},
            {"keyword": "CONNECTIVITY_USE_RESTRICTED_NETWORKS", "info": ["签名|专用", "-", "允许内部用户使用受限网络。"]},
            {"keyword": "CONTROL_DISPLAY_BRIGHTNESS", "info": ["签名", "-", "允许应用控制系统亮度。"]},
            {"keyword": "CONTROL_DISPLAY_SATURATION", "info": ["签名|专用", "-", "允许应用控制颜色饱和度。"]},
            {"keyword": "CONTROL_INCALL_EXPERIENCE", "info": ["签名|专用", "-", "允许应用控制通话体验。"]},
            {"keyword": "CONTROL_KEYGUARD", "info": ["签名", "-", "允许应用控制键盘。"]},
            {"keyword": "CONTROL_REMOTE_APP_TRANSITION_ANIMATIONS", "info": ["签名|专用", "-", "允许应用控制远程动画。对第三方应用不可用。"]},
            {"keyword": "CONTROL_VPN", "info": ["签名|专用", "-", "允许应用控制VPN。对第三方应用不可用。"]},
            {"keyword": "CONTROL_WIFI_DISPLAY", "info": ["签名", "-", "允许应用控制WiFi显示器。"]},
            {"keyword": "CREATE_USERS", "info": ["签名", "-", "允许应用创建用户。对第三方应用不可用。"]},
            {"keyword": "CRYPT_KEEPER", "info": ["签名|专用", "-", "保护访问加密方法。"]},
            {"keyword": "DELETE_PACKAGES", "info": ["签名|专用", "-", "允许应用删除包。"]},
            {"keyword": "DEVICE_POWER", "info": ["签名", "-", "允许访问底层电源管理。对第三方应用不可用。"]},
            {"keyword": "DISABLE_HIDDEN_API_CHECKS", "info": ["签名", "-", "允许在启动进程时禁用隐藏的API检查。对第三方应用不可用。"]},
            {"keyword": "DISABLE_INPUT_DEVICE", "info": ["签名", "-", "允许应用禁用/启用输入设备。"]},
            {"keyword": "DISPATCH_NFC_MESSAGE", "info": ["签名|专用", "-", "允许NFC堆栈向应用发送NFC消息。"]},
            {"keyword": "DISPATCH_PROVISIONING_MESSAGE", "info": ["签名|专用", "-", "允许受信应用管理其他应用设置。"]},
            {"keyword": "DVB_DEVICE", "info": ["签名|专用", "-", "允许TvInputService访问DVB设备。对第三方应用不可用。"]},
            {"keyword": "FILTER_EVENTS", "info": ["签名", "-", "允许应用注册输入过滤器。"]},
            {"keyword": "FORCE_BACK", "info": ["签名", "-", "允许应用强制使用back后退按键，无论Activity是否在顶层。对第三方应用不可用。"]},
            {"keyword": "FORCE_PERSISTABLE_URI_PERMISSIONS", "info": ["签名", "-", "允许应用更改授予其他应用的持久URI权限的状态。对第三方应用不可用。"]},
            {"keyword": "FORCE_STOP_PACKAGES", "info": ["签名|专用", "-", "允许应用调用forceStopPackage。"]},
            {"keyword": "FREEZE_SCREEN", "info": ["签名", "-", "允许应用暂时冻结屏幕以进行全屏切换。"]},
            {"keyword": "GET_APP_GRANTED_URI_PERMISSIONS", "info": ["签名", "-", "允许应用获取其他应用的URI权限。对第三方应用不可用。"]},
            {"keyword": "GET_APP_OPS_STATS", "info": ["签名|专用|开发", "-", "允许应用收集应用操作统计信息。对第三方应用不可用。"]},
            {"keyword": "GET_DETAILED_TASKS", "info": ["签名", "-", "允许应用读取任务详细。"]},
            {"keyword": "GET_INTENT_SENDER_INTENT", "info": ["签名", "-", "允许应用调用PendingIntent.getIntent()。"]},
            {"keyword": "GET_PASSWORD", "info": ["签名", "-", "允许取得用户的密码。"]},
            {"keyword": "GET_PROCESS_STATE_AND_OOM_SCORE", "info": ["签名|专用|开发", "-", "允许应用查询进程状态和当前OOM调整分数。对第三方应用不可用。"]},
            {"keyword": "GET_TOP_ACTIVITY_INFO", "info": ["签名", "-", "允许应用取得顶层Acitivty信息。对第三方应用不可用。"]},
            {"keyword": "GLOBAL_SEARCH_CONTROL", "info": ["签名", "-", "允许访问全局搜索。"]},
            {"keyword": "GRANT_RUNTIME_PERMISSIONS", "info": ["签名|安装|验证", "-", "允许应用授予特定权限。"]},
            {"keyword": "HARDWARE_TEST", "info": ["签名", "-", "访问硬件辅助设备，用于硬件测试。对第三方应用不可用。"]},
            {"keyword": "HDMI_CEC", "info": ["签名|专用", "-", "允许HDMI-CEC服务访问设备和配置文件。这只能由HDMI-CEC服务使用。对第三方应用不可用。"]},
            {"keyword": "HIDE_NON_SYSTEM_OVERLAY_WINDOWS", "info": ["签名|安装", "-", "允许应用隐藏非系统覆盖窗口。对第三方应用不可用。"]},
            {"keyword": "INJECT_EVENTS", "info": ["签名", "-", "允许访问本程序的底层事件，获取按键、轨迹球的事件流。对第三方应用不可用。"]},
            {"keyword": "INSTALL_GRANT_RUNTIME_PERMISSIONS", "info": ["签名|安装|验证", "-", "允许应用请求在安装时授予某些运行时权限。"]},
            {"keyword": "INSTALL_PACKAGE_UPDATES", "info": ["签名|专用", "-", "允许应用安装更新。对第三方应用不可用。"]},
            {"keyword": "INSTALL_SELF_UPDATES", "info": ["签名|专用", "-", "允许应用安装自我更新。对第三方应用不可用。"]},
            {"keyword": "INTERACT_ACROSS_USERS_FULL", "info": ["签名|安装", "-", "允许应用与用户互动。"]},
            {"keyword": "INTERACT_ACROSS_USERS", "info": ["签名|专用|开发", "-", "允许应用与用户互动。对第三方应用不可用。"]},
            {"keyword": "INTERNAL_DELETE_CACHE_FILES", "info": ["签名", "-", "允许应用删除缓存文件。"]},
            {"keyword": "INTERNAL_SYSTEM_WINDOW", "info": ["签名", "-", "允许应用打开系统用户界面。对第三方应用不可用。"]},
            {"keyword": "INVOKE_CARRIER_SETUP", "info": ["签名|专用", "-", "允许应用调用载波设置流。对第三方应用不可用。"]},
            {"keyword": "KILL_UID", "info": ["签名|installer","-","允许应用杀死UID。对第三方应用不可用。"]},
            {"keyword": "LAUNCH_TRUST_AGENT_SETTINGS", "info": ["签名|专用","-","允许应用启动信任代理设置活动。"]},
            {"keyword": "LOCAL_MAC_ADDRESS", "info": ["签名|专用","-","允许读取Wifi和蓝牙的MAC地址。"]},
            {"keyword": "LOCATION_HARDWARE", "info": ["签名|专用","18","允许应用使用硬件位置功能，如地理围栏API。对第三方应用不可用。"]},
            {"keyword": "LOOP_RADIO", "info": ["签名|专用","-","允许应用访问循环无线电设备。"]},
            {"keyword": "MANAGE_ACTIVITY_STACKS", "info": ["签名|专用|开发","-","允许应用管理Activity堆栈。"]},
            {"keyword": "MANAGE_APP_OPS_MODES", "info": ["签名|安装|验证","-","允许更新用户应用操作模式。对第三方应用不可用。"]},
            {"keyword": "MANAGE_APP_OPS_RESTRICTIONS", "info": ["签名|安装","-","允许更新用户应用操作限制。对第三方应用不可用。"]},
            {"keyword": "MANAGE_APP_TOKENS", "info": ["签名","-","允许应用在窗口管理器中管理应用Tokens。"]},
            {"keyword": "MANAGE_AUDIO_POLICY", "info": ["签名","-","允许音频策略管理。"]},
            {"keyword": "MANAGE_AUTO_FILL", "info": ["签名","-","允许应用管理自动填充会话。对第三方应用不可用。"]},
            {"keyword": "MANAGE_BIND_INSTANT_SERVICE", "info": ["签名","-","允许管理系统是否可以绑定到即时应用提供的服务。"]},
            {"keyword": "MANAGE_BLUETOOTH_WHEN_PERMISSION_REVIEW_REQUIRED", "info": ["签名","-","允许在权限检查模式下对蓝牙状态进行内部管理。对第三方应用不可用。"]},
            {"keyword": "MANAGE_CA_CERTIFICATES", "info": ["签名|专用","-","允许应用安装/卸载CA凭证。"]},
            {"keyword": "MANAGE_CAMERA", "info": ["签名","-","允许对摄像头框架进行内部管理。"]},
            {"keyword": "MANAGE_CARRIER_OEM_UNLOCK_STATE", "info": ["签名|专用","-","允许读取和启用/禁用运营商状态允许的OEM解锁。对第三方应用不可用。"]},
            {"keyword": "MANAGE_DEVICE_ADMINS", "info": ["签名|专用","-","允许以管理员身份添加/删除其他应用。对第三方应用不可用。"]},
            {"keyword": "MANAGE_FINGERPRINT", "info": ["签名|专用","-","允许应用管理指纹模板。"]},
            {"keyword": "MANAGE_IPSEC_TUNNELS", "info": ["签名|应用","-","允许应用创建管理IPsec通道。仅对授权应用可用。"]},
            {"keyword": "MANAGE_LOWPAN_INTERFACES", "info": ["签名|专用","-","允许应用注册/卸载LoWPAN。对第三方应用不可用。"]},
            {"keyword": "MANAGE_MEDIA_PROJECTION", "info": ["签名","-","允许应用程序投影会话。对第三方应用不可用。"]},
            {"keyword": "MANAGE_NETWORK_POLICY", "info": ["签名","-","允许应用管理网络策略。"]},
            {"keyword": "MANAGE_NOTIFICATIONS", "info": ["签名","-","允许修改“勿扰”规则和策略。"]},
            {"keyword": "MANAGE_PROFILE_AND_DEVICE_OWNERS", "info": ["签名","-","允许应用管理个人资料和设备所有者。"]},
            {"keyword": "MANAGE_SCOPED_ACCESS_DIRECTORY_PERMISSIONS", "info": ["签名","-","允许应用更改用户授予或拒绝的作用域访问目录请求的状态。对第三方应用不可用。"]},
            {"keyword": "MANAGE_SENSORS", "info": ["签名","-","允许对传感器框架进行内部管理。"]},
            {"keyword": "MANAGE_SLICE_PERMISSIONS", "info": ["签名","-","允许SysUI管理用户授权。"]},
            {"keyword": "MANAGE_SOUND_TRIGGER", "info": ["签名|专用","-","允许访问声音触发API。"]},
            {"keyword": "MANAGE_SUBSCRIPTION_PLANS", "info": ["签名|专用","-","允许应用管理运营商订阅计划。"]},
            {"keyword": "MANAGE_USB", "info": ["签名|专用","-","允许应用管理USB设备的首选项和权限。"]},
            {"keyword": "MANAGE_USER_OEM_UNLOCK_STATE", "info": ["签名|专用","-","允许读取和启用/禁用用户状态允许的OEM解锁。对第三方应用不可用。"]},
            {"keyword": "MANAGE_USERS", "info": ["签名|专用","-","允许应用管理用户。对第三方应用不可用。"]},
            {"keyword": "MANAGE_VOICE_KEYPHRASES", "info": ["签名|专用","-","允许应用注册Hotword。对第三方应用不可用。"]},
            {"keyword": "MANAGE_WIFI_WHEN_PERMISSION_REVIEW_REQUIRED", "info": ["签名","-","允许在权限检查模式下对Wi-Fi连接状态进行管理。对第三方应用不可用。"]},
            {"keyword": "MODIFY_ACCESSIBILITY_DATA", "info": ["签名","-","允许应用修改其他应用的辅助功能。"]},
            {"keyword": "MODIFY_APPWIDGET_BIND_PERMISSIONS", "info": ["签名|专用","-","允许应用访问AppWidgets。"]},
            {"keyword": "MODIFY_AUDIO_ROUTING", "info": ["签名|专用","-","允许应用修改音频路由和覆盖策略。对第三方应用不可用。"]},
            {"keyword": "MODIFY_CELL_BROADCASTS", "info": ["签名|专用","-","允许应用通过内容提供程序修改单元广播。对第三方应用不可用。"]},
            {"keyword": "MODIFY_DAY_NIGHT_MODE", "info": ["签名|专用","-","允许修改夜晚模式。"]},
            {"keyword": "MODIFY_PARENTAL_CONTROLS", "info": ["签名|专用","-","允许应用修改家长控制。对第三方应用不可用。"]},
            {"keyword": "MODIFY_QUIET_MODE", "info": ["签名|专用","-","允许应用打开/关闭静音模式。对第三方应用不可用。"]},
            {"keyword": "MODIFY_THEME_OVERLAY", "info": ["签名","-","允许应用覆盖正在使用的主题。对第三方应用不可用。"]},
            {"keyword": "MOVE_PACKAGE", "info": ["签名|专用","-","允许应用移动已安装包的位置。"]},
            {"keyword": "NET_ADMIN", "info": ["签名","-","允许访问配置网络接口、配置/使用IPSec等。"]},
            {"keyword": "NET_TUNNELING", "info": ["签名","-","允许低级别访问tun tap驱动程序。"]},
            {"keyword": "NETWORK_BYPASS_PRIVATE_DNS", "info": ["签名","-","允许应用绕过专用DNS。对第三方应用不可用。"]},
            {"keyword": "NETWORK_SETTINGS", "info": ["签名","-","允许应用设置和SystemUI调用网络服务。对第三方应用不可用。"]},
            {"keyword": "NETWORK_SETUP_WIZARD", "info": ["签名|设置","-","允许设置向导调用网络服务。对第三方应用不可用。"]},
            {"keyword": "NETWORK_STACK", "info": ["签名","-","允许应用访问网络堆栈服务。对第三方应用不可用。"]},
            {"keyword": "NFC_HANDOVER_STATUS", "info": ["签名|专用","-","允许从WiFi和蓝牙发送和接收切换传输状态。"]},
            {"keyword": "NOTIFICATION_DURING_SETUP", "info": ["签名|专用","-","允许应用在设置设备之前显示通知。对第三方应用不可用。"]},
            {"keyword": "NOTIFY_PENDING_SYSTEM_UPDATE", "info": ["签名|专用","-","允许系统更新服务通知设备所有者挂起的更新。对第三方应用不可用。"]},
            {"keyword": "NOTIFY_TV_INPUTS", "info": ["签名|专用","-","允许应用通过发送广播通知电视输入。对第三方应用不可用。"]},
            {"keyword": "OBSERVE_APP_USAGE", "info": ["签名|专用","-","允许应用观察应用的使用时间。"]},
            {"keyword": "OBSERVE_GRANT_REVOKE_PERMISSIONS", "info": ["签名|专用","-","允许应用观察权限更改。"]},
            {"keyword": "OEM_UNLOCK_STATE", "info": ["签名","-","允许启用/禁用OEM解锁。对第三方应用不可用。"]},
            {"keyword": "OPEN_APPLICATION_DETAILS_OPEN_BY_DEFAULT_PAGE", "info": ["签名","-","允许应用直接打开详细屏幕内的“默认”页面。对第三方应用不可用。"]},
            {"keyword": "OVERRIDE_WIFI_CONFIG", "info": ["签名|专用","-","允许应用修改任何WiFi配置。对第三方应用不可用。"]},
            {"keyword": "PACKAGE_VERIFICATION_AGENT", "info": ["签名|专用","-","包验证程序必要。"]},
            {"keyword": "PACKET_KEEPALIVE_OFFLOAD", "info": ["签名|专用","-","允许系统应用访问硬件包卸载功能。"]},
            {"keyword": "PEERS_MAC_ADDRESS", "info": ["签名|设置","-","允许访问Wifi和蓝牙配对设备的MAC地址。"]},
            {"keyword": "PERFORM_CDMA_PROVISIONING", "info": ["签名|专用","-","允许应用执行CDMA OTA配置"]},
            {"keyword": "PERFORM_SIM_ACTIVATION", "info": ["签名|专用","-","允许应用激活SIM。"]},
            {"keyword": "PROVIDE_RESOLVER_RANKER_SERVICE", "info": ["签名|专用","-","允许应用扩展ResolverRankerService。"]},
            {"keyword": "PROVIDE_TRUST_AGENT", "info": ["签名|专用","-","允许应用提供信任代理。"]},
            {"keyword": "QUERY_DO_NOT_ASK_CREDENTIALS_ON_BOOT", "info": ["签名","-","允许应用查询DO_NOT_ASK_CREDENTIALS_ON_BOOT的应用。"]},
            {"keyword": "QUERY_TIME_ZONE_RULES", "info": ["签名|专用","-","允许应用查询当前时区规则。"]},
            {"keyword": "READ_BLOCKED_NUMBERS", "info": ["签名","-","允许读取被拦截号码。"]},
            {"keyword": "READ_CONTENT_RATING_SYSTEMS", "info": ["签名|专用","-","允许应用读取TvContentRatingSystemInfo。对第三方应用不可用。"]},
            {"keyword": "READ_DREAM_STATE", "info": ["签名|专用","-","允许应用读取休眠设置。"]},
            {"keyword": "READ_INSTALL_SESSIONS", "info": ["正常","-","允许应用读取安装会话。对第三方应用不可用。"]},
            {"keyword": "READ_LOWPAN_CREDENTIAL", "info": ["签名|专用","-","允许应用读取LoWPAN凭证。对第三方应用不可用。"]},
            {"keyword": "READ_NETWORK_USAGE_HISTORY", "info": ["签名|专用","-","允许应用读取特定网络和历史使用情况。"]},
            {"keyword": "READ_OEM_UNLOCK_STATE", "info": ["签名|专用","-","允许读取OEM解锁状态。对第三方应用不可用。"]},
            {"keyword": "READ_PRECISE_PHONE_STATE", "info": ["签名|专用","-","允许只读访问精确的电话状态。"]},
            {"keyword": "READ_PRINT_SERVICE_RECOMMENDATIONS", "info": ["签名|预安装","-","允许应用获取当前推荐的打印服务。"]},
            {"keyword": "READ_PRINT_SERVICES", "info": ["签名|预安装","-","允许应用获取已安装和启用的打印服务。"]},
            {"keyword": "READ_PRIVILEGED_PHONE_STATE", "info": ["签名|专用","-","允许读取专用电话状态。对第三方应用不可用。"]},
            {"keyword": "READ_RUNTIME_PROFILES", "info": ["签名|专用","-","允许应用读取其他应用的运行时配置文件。对第三方应用不可用。"]},
            {"keyword": "READ_SEARCH_INDEXABLES", "info": ["签名|专用","-","允许应用读取可索引数据。"]},
            {"keyword": "READ_SYSTEM_UPDATE_INFO", "info": ["签名","-","允许应用读取系统更新信息。"]},
            {"keyword": "READ_WALLPAPER_INTERNAL", "info": ["签名|专用","-","允许应用读取系统壁纸图片。对第三方应用不可用。"]},
            {"keyword": "READ_WIFI_CREDENTIAL", "info": ["签名|专用","-","允许应用读取Wi-Fi凭证。对第三方应用不可用。"]},
            {"keyword": "REAL_GET_TASKS", "info": ["签名|专用","-","允许应用使用新版本GET_TASKS。"]},
            {"keyword": "RECEIVE_BLUETOOTH_MAP", "info": ["签名|专用","-","允许应用监视传入的蓝牙地图信息。"]},
            {"keyword": "RECEIVE_DATA_ACTIVITY_CHANGE", "info": ["签名|专用","-",""]},
            {"keyword": "RECEIVE_EMERGENCY_BROADCAST", "info": ["签名|专用","-","允许应用接收紧急蜂窝广播消息。对第三方应用不可用。"]},
            {"keyword": "RECEIVE_MEDIA_RESOURCE_USAGE", "info": ["签名|专用","-","允许接收媒体资源的使用。"]},
            {"keyword": "RECEIVE_STK_COMMANDS", "info": ["签名|专用","-","允许应用接收STK相关的命令。"]},
            {"keyword": "RECEIVE_WIFI_CREDENTIAL_CHANGE", "info": ["签名|专用","-","允许系统应用接收WiFi凭证更改广播。对第三方应用不可用。"]},
            {"keyword": "RECOVER_KEYSTORE", "info": ["签名|专用","-","允许应用管理RecoveryController。对第三方应用不可用。"]},
            {"keyword": "RECOVERY", "info": ["签名|专用","-","允许应用还原系统。"]},
            {"keyword": "REGISTER_CALL_PROVIDER", "info": ["签名|专用","-","允许应用注册通话提供者。"]},
            {"keyword": "REGISTER_CONNECTION_MANAGER", "info": ["签名|专用","-","允许应用注册连接管理。"]},
            {"keyword": "REGISTER_SIM_SUBSCRIPTION", "info": ["签名|专用","-","允许应用注册SIM订阅。"]},
            {"keyword": "REGISTER_WINDOW_MANAGER_LISTENERS", "info": ["签名","-","允许从窗口管理器注册事件的侦听器。"]},
            {"keyword": "REMOTE_AUDIO_PLAYBACK", "info": ["签名","-","允许注册远程音频播放。"]},
            {"keyword": "REMOVE_DRM_CERTIFICATES", "info": ["签名|专用","-","允许应用移除DRM凭证。对第三方应用不可用。"]},
            {"keyword": "REMOVE_TASKS", "info": ["签名","-","允许应用删除任务。"]},
            {"keyword": "REQUEST_NETWORK_SCORES", "info": ["签名|设置","-","允许应用从NetworkScoreService请求网络建议和分数。对第三方应用不可用。"]},
            {"keyword": "RESET_FINGERPRINT_LOCKOUT", "info": ["签名","-","允许应用重置指纹尝试计数器。"]},
            {"keyword": "RESET_SHORTCUT_MANAGER_THROTTLING", "info": ["签名","-","允许应用重置快捷方式。"]},
            {"keyword": "RESTRICTED_VR_ACCESS", "info": ["签名|预安装","-","允许访问VR-API。"]},
            {"keyword": "RETRIEVE_WINDOW_CONTENT", "info": ["签名|专用","-","允许应用检索活动窗口的内容。"]},
            {"keyword": "RETRIEVE_WINDOW_TOKEN", "info": ["签名","-","允许应用从辅助功能管理器检索窗口令牌。"]},
            {"keyword": "REVOKE_RUNTIME_PERMISSIONS", "info": ["签名|安装|验证","-","允许应用撤消特定权限。"]},
            {"keyword": "RUN_IN_BACKGROUND", "info": ["签名","-","允许应用在后台运行。"]},
            {"keyword": "SCORE_NETWORKS", "info": ["签名|专用","-","允许应用程序充当网络记分员。"]},
            {"keyword": "SEND_EMBMS_INTENTS", "info": ["签名|专用","-","允许应用发送EMBMS下载信息。"]},
            {"keyword": "SEND_SHOW_SUSPENDED_APP_DETAILS", "info": ["签名","-","允许应用发送显示挂起应用详细。对第三方应用不可用。"]},
            {"keyword": "SEND_SMS_NO_CONFIRMATION", "info": ["签名|专用","-","允许应用在用户未确认一下发送短码消息。对第三方应用不可用。"]},
            {"keyword": "SERIAL_PORT", "info": ["签名|专用","-","允许应用通过SerialManager访问串行端口。"]},
            {"keyword": "SET_ACTIVITY_WATCHER", "info": ["签名","-","允许应用监视和控制如何在系统中全局启动活动。"]},
            {"keyword": "SET_DISPLAY_OFFSET", "info": ["签名|专用","-","允许应用设置屏幕的显示偏移。对第三方应用不可用。"]},
            {"keyword": "SET_HARMFUL_APP_WARNINGS", "info": ["签名|verifier","-","允许应用将其他应用标记为有害。"]},
            {"keyword": "SET_INPUT_CALIBRATION", "info": ["签名","-","设置输入校准。对第三方应用不可用。"]},
            {"keyword": "SET_KEYBOARD_LAYOUT", "info": ["签名","-","设置键盘布局。对第三方应用不可用。"]},
            {"keyword": "SET_MEDIA_KEY_LISTENER", "info": ["签名|专用|开发","-","允许应用设置媒体密钥事件侦听器。"]},
            {"keyword": "SET_ORIENTATION", "info": ["签名","-","设置横屏。对第三方应用不可用。"]},
            {"keyword": "SET_POINTER_SPEED", "info": ["签名","-","设置点击速度。对第三方应用不可用。"]},
            {"keyword": "SET_SCREEN_COMPATIBILITY", "info": ["签名","-","允许应用更改屏幕兼容性模式。"]},
            {"keyword": "SET_VOLUME_KEY_LONG_PRESS_LISTENER", "info": ["签名|专用|开发","-","允许应用设置音量键长按监听器。"]},
            {"keyword": "SET_WALLPAPER_COMPONENT", "info": ["签名|专用","-","允许应用设置实时壁纸。"]},
            {"keyword": "SHOW_KEYGUARD_MESSAGE", "info": ["签名|专用","-","允许应用解除键盘上的信息。"]},
            {"keyword": "SHUTDOWN", "info": ["签名|专用","-","允许关机。"]},
            {"keyword": "START_ANY_ACTIVITY", "info": ["签名","-","允许应用启动任何Activity。"]},
            {"keyword": "START_TASKS_FROM_RECENTS", "info": ["签名|专用","-","允许应用启动任务。"]},
            {"keyword": "STATSCOMPANION", "info": ["签名","-","允许应用管理statcomponent。对第三方应用不可用。"]},
            {"keyword": "STATUS_BAR_SERVICE", "info": ["签名","-","允许应用成为状态栏。"]},
            {"keyword": "STOP_APP_SWITCHES", "info": ["签名|专用","-","允许应用停止应用程序切换。"]},
            {"keyword": "STORAGE_INTERNAL", "info": ["签名","-","内部存储。"]},
            {"keyword": "SUBSTITUTE_NOTIFICATION_APP_NAME", "info": ["签名|专用","-","允许应用替换N以上版本中旁边通知的应用名称。对第三方应用不可用。"]},
            {"keyword": "SUSPEND_APPS", "info": ["签名|专用","-","允许应用挂起其他应用。"]},
            {"keyword": "TABLET_MODE", "info": ["签名","-","允许应用查询Tablet模式状态并监视更改。对第三方应用不可用。"]},
            {"keyword": "TEMPORARY_ENABLE_ACCESSIBILITY", "info": ["签名","-","允许应用临时启用可访问性。"]},
            {"keyword": "TEST_BLACKLISTED_PASSWORD", "info": ["签名","-","允许测试管理员是否禁止密码。对第三方应用不可用。"]},
            {"keyword": "TETHER_PRIVILEGED", "info": ["签名|专用","-","允许应用更改捆绑状态并捆绑运营商。对第三方应用不可用。"]},
            {"keyword": "TRIGGER_TIME_ZONE_RULES_CHECK", "info": ["签名","-","允许应用修改时区规则。确保只有系统可以绑定到它。"]},
            {"keyword": "TRUST_LISTENER", "info": ["签名","-","允许应用侦听信任更改。"]},
            {"keyword": "TV_INPUT_HARDWARE", "info": ["签名|专用","-","允许TvInputService访问基础的电视输入硬件。"]},
            {"keyword": "TV_VIRTUAL_REMOTE_CONTROLLER", "info": ["签名|专用","-","电视的虚拟遥控器必要。对第三方应用不可用。"]},
            {"keyword": "UNLIMITED_SHORTCUTS_API_CALLS", "info": ["签名|文本分类器","-","允许无限制地调用快捷方式变异API。"]},
            {"keyword": "UPDATE_APP_OPS_STATS", "info": ["签名|专用|安装","-","允许更新应用操作统计信息。对第三方应用不可用。"]},
            {"keyword": "UPDATE_CONFIG", "info": ["签名|专用","-","允许应用启动配置更新。"]},
            {"keyword": "UPDATE_LOCK_TASK_PACKAGES", "info": ["签名|设置","-","允许应用在锁定任务模式期间白名单任务。对第三方应用不可用。"]},
            {"keyword": "UPDATE_LOCK", "info": ["签名|专用","-","允许应用持有一个UpdateLock。"]},
            {"keyword": "UPDATE_TIME_ZONE_RULES", "info": ["签名|专用","-","允许应用请求系统安装/卸载时区规则。"]},
            {"keyword": "USE_COLORIZED_NOTIFICATIONS", "info": ["签名|设置","-","允许应用着色通知。对第三方应用不可用。"]},
            {"keyword": "USE_DATA_IN_BACKGROUND", "info": ["签名","-","允许应用在后台使用数据。"]},
            {"keyword": "USE_RESERVED_DISK", "info": ["签名|专用","-","允许应用使用保留的磁盘空间。对第三方应用不可用。"]},
            {"keyword": "USER_ACTIVITY", "info": ["签名|专用","-","允许访问PowerManager.userActivity。对第三方应用不可用。"]},
            {"keyword": "VIEW_INSTANT_APPS", "info": ["签名|预安装","-","允许查看设备上的即时应用。"]},
            {"keyword": "WATCH_APPOPS", "info": ["签名","-","允许应用监视更改 和/或 活动状态。对第三方应用不可用。"]},
        ]

        matched_infos = []
        for item in info_array:
            if item["keyword"] == input_str:
                matched_infos.extend(item["info"])
                return matched_infos[0],matched_infos[1],matched_infos[2]     
        return None

    def get_permission_info(self,path):
        data = []
        res=[]
        with open(path, 'r') as f:
            content = json.load(f)
            # print(content)
        data=content["Permissions"]
        for string in data:
            last_dot_index = string.rfind('.')
            if last_dot_index != -1:
                result = string[last_dot_index+1:]
            else:
                result = string
            res.append(result)
        return res
    
    def get_permission_des(self,jsonname,jsonpath):
        path=os.path.join(jsonpath,jsonname)
        data=self.get_permission_info(path)
        a="此app无风险权限"
        b="此app有风险权限"
        des_list=[]
        flag=False
        for d in data:
            # print(d)
            out=self.permisson_des(d)
            print(out)
            if out!=None:
                type,level,des=out
                string= "权限名称："+d+" 类型："+type+" 等级："+level+" 描述："+des
                des_list.append(string)
                if type=="危险":
                    flag=True
        # print(des_list)
        if flag:
            des_list.append(b)
            return des_list,'danger'
        else:
            des_list.append(a)
            return des_list,'safe'
    
    
    
    
    def get_judge_result(self,type,Permissions):
        
        def get_scg(y):
            if y==0:
                return 'sex'
            elif y==1:
                return 'scam'
            elif y==2:
                return 'gamble'
        def get_roy(y):
            if y==0:
                return 'black'
            elif y==1:
                return 'grey'
            elif y==2:
                return 'white'
            
        if type=="roy":
            res= apk_predict(type,Permissions)
            return get_roy(res)
            
        elif type=="scg":
            res= apk_predict(type,Permissions)
            return get_scg(res)
            
            
        
        